In [2]:
import pandas as pd
from pathlib import Path

In [3]:
in_kwds = '../data/full_04_01_2020/all_keywords_threshold_300_1.5_10000.jsonl'

In [5]:
df = pd.read_json(in_kwds, orient='records', lines=True)

In [8]:
df.sort_values(by='doc_id_count', ascending=False)

stem  rake_score_mean  doc_id_count  \
5039               ion         1.505022       1603531   
5010               lat         1.523537        494335   
4377   available <p />         4.003793        345835   
4859              star         1.658931        307170   
4972              mode         1.547764        306794   
...                ...              ...           ...   
2794  geometric albedo         4.236874           301   
1121       cygnus loop         4.622487           301   
944     imaging system         4.734689           301   
3275  localized region         4.161024           301   
3798    subsolar point         4.080483           301   

                                            doc_id_list  \
5039  [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 7, 7, ...   
5010  [0, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...   
4377  [101, 127, 195, 234, 251, 340, 426, 441, 483, ...   
4859  [1, 1, 3, 4, 5, 5, 6, 6, 7, 7, 8, 8, 11, 11, 1...   
4972  [0, 3, 8, 11, 12, 12, 13, 14, 16, 18, 19, 19, ...   
...                                                 ...   
2794  [4294, 8724, 9602, 9711, 19469, 22681, 23945, ...   
1121  [1983, 4839, 9308, 10223, 18943, 23731, 25408,...   
944   [4999, 7365, 16436, 21217, 21757, 24432, 24638...   
3275  [2831, 2895, 3806, 4076, 15865, 18736, 19160, ...   
3798  [5317, 5480, 8006, 8253, 11059, 13768, 16532, ...   

                                           keyword_list  nasa_afil  1986_sum  \
5039                                        [ions, ion]   0.012737     37004   
5010                                              [lat]   0.016145      9941   
4377                                  [available <p />]   0.000090     12876   
4859  [starred, star e, stars, star s, star, star fu...   0.015887      6895   
4972       [modeli, moded, mode, moding, mode e, modes]   0.019463      5485   
...                                                 ...        ...       ...   
2794  [geometric albedoes, geometric albedos, geomet...   0.009967         8   
1121                                      [cygnus loop]   0.023256        12   
944                   [imaging system, imaging systems]   0.000000         2   
3275              [localized regions, localized region]   0.033223        10   
3798                  [subsolar point, subsolar points]   0.029900        10   

      1987_sum  1988_sum  1989_sum  ...  2001_sum  2002_sum  2003_sum  \
5039     37594     38457     38201  ...     72388     77155     82139   
5010      9844     10211     10214  ...     23337     25658     25943   
4377     14302     14541     15830  ...     13125     10714     12288   
4859      7116      6796      6220  ...     13862     13637     16546   
4972      5520      5690      5716  ...     14782     15772     16447   
...        ...       ...       ...  ...       ...       ...       ...   
2794        10         5         8  ...         9        13        21   
1121         5        12         5  ...        15        13        14   
944          4         4         6  ...        11        12        11   
3275         9         8         3  ...        18        21        21   
3798         3        10         4  ...        12        18        14   

      2004_sum  2005_sum  2006_sum  2007_sum  2008_sum  2009_sum  2010_sum  
5039     90058     86372     97494     88061    100586     93162    105202  
5010     28817     26983     31564     27865     32394     29309     34210  
4377     10557     15297     13484     12302     14065     15296     12437  
4859     16875     16850     18306     18074     18002     17401     20108  
4972     18461     17136     19949     17789     20608     18917     22166  
...        ...       ...       ...       ...       ...       ...       ...  
2794        20        14        17        16        19        17        15  
1121        13        12        13         6        12        12        15  
944         21        21        23        16        20        20        15  
3275        15  

# Available

In [15]:
s = "available <p />"

In [28]:
avail_docs = df.query(f'stem == "{s}"').doc_id_list.iloc[0]

In [54]:
avail_docs[0:10]

[101, 127, 195, 234, 251, 340, 426, 441, 483, 500]

In [152]:
av = np.array(avail_docs)

In [136]:
len(avail_docs)

345835

In [52]:
# Increment by 1 when working with sed since file is 1 index and dataframe index starts with 0

In [55]:
! sed -n 102p ../data/full_04_01_2020/kwds.jsonl | jq [".abstract"]

[
  "Not Available <P />"
]


In [56]:
! sed -n 128p ../data/full_04_01_2020/kwds.jsonl | jq [".abstract"]

[
  "Not Available <P />"
]


In [53]:
# "available <p />" token indicates that the abstract is not available. These shoudl be excluded from the datasets at the onset.

# <> tags and other HTML

In [91]:
df[df['stem'].str.contains('<')].stem.tolist() #.apply(strip_tags).tolist()

['c<sub>2</sub>h<sub>2</sub>',
 'h <sub>2</sub>o',
 'b<sub>z</sub>',
 'h<sub>2</sub>co',
 'ch<sub>3</sub>oh',
 'h<sub>2</sub>o',
 'c<sup>18</sup>o',
 'ω<sub>m</sub>',
 't<sub>eff</sub>',
 'km s<sup>-1</sup>',
 '5 km s<sup>-1</sup>',
 'h <sub>2</sub>',
 'h<sub>2</sub>',
 'ch <sub>4</sub>',
 'co <sub>2</sub>',
 'ch<sub>4</sub>',
 '<sup>13</sup>c',
 'o<sub>2</sub>',
 'n<sub>2</sub>',
 'nh<sub>3</sub>',
 '<sup>13</sup>co',
 'co<sub>2</sub>',
 'hco<sup>+</sup>',
 'o<sup>+</sup>',
 'h<sub>0</sub>',
 'o<sub>3</sub>',
 '<sup>12</sup>co',
 'h<sup>+</sup>',
 '<sup>26</sup>',
 'c<sub>2</sub>',
 '<sup>12</sup>c',
 '<sup>16</sup>o',
 '<sup>7</sup>li',
 '<p /><p /><p />',
 '<p />e-mail',
 '<sup>1</sup>',
 '<sub>4</sub>',
 '<sup>-1</sup>',
 '<sub>2</sub>',
 '<sup>2</sup>',
 'm<sub>',
 '<sup>+</sup>',
 '<sub>0</sub>',
 '10<sup>4</sup>',
 '<sup>4</sup>',
 '10<sup>-4</sup>',
 '<sup>10</sup>',
 '<sup>3</sup>',
 '<sup>7</sup>',
 '<p /><p />',
 '<p />base',
 '<br />method',
 '<br />conclus',
 'available <p

In [65]:
s = "<br />"
s_docs = df.query(f'stem == "{s}"').doc_id_list.iloc[0]

In [66]:
s_docs[0:10]

[43047, 50550, 53768, 69217, 70791, 71549, 148676, 179001, 367318, 476680]

In [67]:
! sed -n 50551p ../data/full_04_01_2020/kwds.jsonl | jq [".abstract"]

[
  "The Ulysses observations have charted the heliosphere around the minimum in the 11 year cycle of solar activity, revealing the large scale properties of the heliospheric medium and its micro-scale characteristics. This book presents for the first time, a comprehensive review of the results of the Ulysses mission.<BR />The first chapter provides an overview of the region, introducing the heliosphere prior to the Ulysses mission, and the objectives and characteristics of the mission itself. Subsequent chapters discuss in detail specific areas of the heliosphere, including the solar wind, large and small scale features, cosmic rays and energetic particles, and the observations of interstellar gas and cosmic dust. Each of these chapters is written by members of the Ulysses science team, concentrating on their own areas of expertise, and is written in a clear and accessible way.<BR />In this book, the authors aim to summarise our understanding of the heliosphere near solar minimum and 

In [68]:
from html.parser import HTMLParser

In [70]:
class MLStripper(HTMLParser):
    def __init__(self):
        super().__init__()
        self.reset()
        self.fed = []
        
    def handle_data(self, d):
        self.fed.append(d)
        
    def get_data(self):
        return ''.join(self.fed)

def strip_tags(html):
    s = MLStripper()
    s.feed(html)
    return s.get_data()

In [73]:
txt = "The Ulysses observations have charted the heliosphere around the minimum in the 11 year cycle of solar activity, revealing the large scale properties of the heliospheric medium and its micro-scale characteristics. This book presents for the first time, a comprehensive review of the results of the Ulysses mission.<BR />The first chapter provides an overview of the region, introducing the heliosphere prior to the Ulysses mission, and the objectives and characteristics of the mission itself. Subsequent chapters discuss in detail specific areas of the heliosphere, including the solar wind, large and small scale features, cosmic rays and energetic particles, and the observations of interstellar gas and cosmic dust. Each of these chapters is written by members of the Ulysses science team, concentrating on their own areas of expertise, and is written in a clear and accessible way.<BR />In this book, the authors aim to summarise our understanding of the heliosphere near solar minimum and to provide the basis for understanding the more complex state of the heliosphere around solar maximum, which will be observed during the next phase of the Ulysses mission. <P />"

In [75]:
%%timeit
strip_tags(txt)

22.9 µs ± 131 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [78]:
22.9e-6  + (131e-9 * 1e6)

0.1310229

In [79]:
# Could use this method is very quickly remove all html tags

# Short Abstracts

In [122]:
from tqdm.notebook import tqdm
import numpy as np

In [94]:
in_corp = Path('../data/full_04_01_2020/kwds.jsonl')

In [98]:
!head -n1 '../data/full_04_01_2020/kwds.jsonl' | jq

{
  "arxiv_class": [
    "astro-ph"
  ],
  "alternate_bibcode": [
    "1996astro.ph.11107N"
  ],
  "bibcode": "1997ApJ...490..493N",
  "keyword": [
    "Cosmology: Theory",
    "Cosmology: Dark Matter",
    "Galaxies: Halos",
    "Methods: Numerical",
    "Astrophysics"
  ],
  "database": [
    "astronomy"
  ],
  "ack": "We are grateful for the hospitality of the Institute for Theoretical Physics of the University of California at Santa Barbara, where some of the work presented here was carried out. J. F. N. is also grateful for the hospitality of the Max‐Planck‐Institut für Astrophysik in Garching, Germany, where this project was started. In addition, he would like to acknowledge useful discussions with Cedric Lacey. Special thanks are due to Shaun Cole for making the data shown in Figure 9 available in electronic form. This work was supported in part by the PPARC and by the NSF under grant PHY94‐07194 to the Institute for Theoretical Physics of the University of California at Santa B

In [196]:
chunks = pd.read_json(in_corp, orient='records', lines=True, chunksize=10_000)

In [197]:
all_short = []
for c in tqdm(chunks):
     all_short += c.index[c['abstract'].apply(lambda x: len(x) < 50)].tolist()

In [200]:
asa = np.array(all_short)
asa

array([    101,     127,     195, ..., 1160534, 1160537, 1160774])

In [201]:
asa.shape

(347850,)

In [202]:
! sed -n 128p ../data/full_04_01_2020/kwds.jsonl | jq [".abstract"]

[
  "Not Available <P />"
]


In [203]:
# c.index[c['abstract'].apply(lambda x: len(x) < 50)]

In [204]:
is_av = np.array(df[df.stem.str.contains('>abstract available</')].doc_id_list.iloc[0])

In [205]:
is_av[0:10]

array([ 56188,  65511,  68380,  93179, 137834, 141213, 151697, 153531,
       164757, 222829])

In [206]:
! sed -n 65512p ../data/full_04_01_2020/kwds.jsonl | jq [".abstract"]

[
  "<A href=\"/journals/ja/ja0103/2000JA000303/0.html\">Abstract Available</A> from <A href=\"http://www.agu.org\">AGU</A> <P />"
]


In [207]:
txt = "<A href=\"/journals/ja/ja0103/2000JA000303/0.html\">Abstract Available</A> from <A href=\"http://www.agu.org\">AGU</A> <P />"

In [208]:
strip_tags(txt)

'Abstract Available from AGU '

In [209]:
av

array([    101,     127,     195, ..., 1160531, 1160534, 1160537])

In [210]:
np.setdiff1d(asa, av)

array([   9883,   14344,   14553, ..., 1158212, 1159259, 1160774])

In [215]:
! sed -n 1158213p ../data/full_04_01_2020/kwds.jsonl | jq [".abstract"]

[
  "Image of Pickering's Triangle on 2010 Aug 8 <P />"
]


In [218]:
# Remove papers with short abstracts. They are not useful.

# Other

In [221]:
! sed -n 5058p ../data/full_04_01_2020/kwds.jsonl | jq [".abstract"]

[
  "By using the IMAGE magnetometer network data, we compare the geomagnetic variation field B and its time derivative dB/dt in and near the auroral region. We show that although the auroral electrojet is the main reason for large B's, it cannot alone produce large dB/dt's, so smaller-scale current systems are important. This is evidenced by the horizontal field: the geographic north component (X) is clearly larger than the eastward one (Y) in the auroral region, but dX/dt and dY/dt are nearly equal. This result is important when geomagnetic induction risks on man-made conductors are estimated. The key quantity is the horizontal geoelectric field, and contrary to what is often assumed, it can have large values in any direction, not just parallel to the electrojet. <P />"
]
